name: Update pxt.json file

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    update-pxt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.13

            - name: Run script
              run: python3 scripts/generate-pxt.py

            - name: check for changes
              id: git-check
              run: |
                  if git diff --quiet; then
                    echo "No changes detected, exiting workflow successfully"
                    exit 0
                  fi
                  echo "changes=true" >> $GITHUB_OUTPUT

            - name: Push to git
              if: steps.git-check.outputs.changes == 'true'
              run: |
                echo "Commiting and pushing new pxt.json"
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "Update pxt.json"
                git push

    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                  .github

            - name: Get prior version
              uses: JamesIves/fetch-api-data-action@v2
              with:
                endpoint: https://api.github.com/repos/CausewayDigital/Minecraft-EE-MakeCode/releases?per_page=1&page=1
                configuration: '{ "method": "GET", "headers": {"accept": "application/vnd.github+json", "X-GitHub-Api-Version":"2022-11-28"}}'
                variable-name: prior_release_data

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.13

            - name: Get new version
              id: next-version
              run: |
                echo "next_version=$(python3 .github/scripts/next-version.py)" >> $GITHUB_OUTPUT

            - name: Create a Release
              uses: elgohr/Github-Release-Action@v5
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                title: ${{steps.next-version.outputs.next_version}}
                tag: ${{steps.next-version.outputs.next_version}}
